/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/icons/AboutMe.vue')['default']
    AboutMeIcon: typeof import('./src/components/icons/AboutMeIcon.vue')['default']
    ContactIcon: typeof import('./src/components/icons/ContactIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeaderContainer: typeof import('./src/components/layout/HeaderContainer.vue')['default']
    HowToUse: typeof import('./src/components/icons/HowToUse.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoginBox: typeof import('./src/components/dialogs/LoginBox.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    Recorder: typeof import('./src/components/dialogs/Recorder.vue')['default']
    RegisterBox: typeof import('./src/components/dialogs/RegisterBox.vue')['default']
    RouterBack: typeof import('./src/components/RouterBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitLine: typeof import('./src/components/SplitLine.vue')['default']
    UsageBox: typeof import('./src/components/dialogs/UsageBox.vue')['default']
    UsageIcon: typeof import('./src/components/icons/UsageIcon.vue')['default']
    UserBox: typeof import('./src/components/dialogs/UserBox.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
