/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/draw/': RouteRecordInfo<'/draw/', '/draw', Record<never, never>, Record<never, never>>,
    '/draw/components/MaterialContainer': RouteRecordInfo<'/draw/components/MaterialContainer', '/draw/components/MaterialContainer', Record<never, never>, Record<never, never>>,
    '/draw/components/MaterialList': RouteRecordInfo<'/draw/components/MaterialList', '/draw/components/MaterialList', Record<never, never>, Record<never, never>>,
    '/draw/components/TemplateContainer': RouteRecordInfo<'/draw/components/TemplateContainer', '/draw/components/TemplateContainer', Record<never, never>, Record<never, never>>,
    '/draw/components/tools/ExtendDraw': RouteRecordInfo<'/draw/components/tools/ExtendDraw', '/draw/components/tools/ExtendDraw', Record<never, never>, Record<never, never>>,
    '/draw/components/tools/MaskRedraw': RouteRecordInfo<'/draw/components/tools/MaskRedraw', '/draw/components/tools/MaskRedraw', Record<never, never>, Record<never, never>>,
    '/draw/components/tools/StyleRedraw': RouteRecordInfo<'/draw/components/tools/StyleRedraw', '/draw/components/tools/StyleRedraw', Record<never, never>, Record<never, never>>,
    '/editor/': RouteRecordInfo<'/editor/', '/editor', Record<never, never>, Record<never, never>>,
    '/editor/components/attributes/AttributeContainer': RouteRecordInfo<'/editor/components/attributes/AttributeContainer', '/editor/components/attributes/AttributeContainer', Record<never, never>, Record<never, never>>,
    '/editor/components/attributes/color/ColorPicker': RouteRecordInfo<'/editor/components/attributes/color/ColorPicker', '/editor/components/attributes/color/ColorPicker', Record<never, never>, Record<never, never>>,
    '/editor/components/attributes/items/AttrCol': RouteRecordInfo<'/editor/components/attributes/items/AttrCol', '/editor/components/attributes/items/AttrCol', Record<never, never>, Record<never, never>>,
    '/editor/components/attributes/items/AudioAttr': RouteRecordInfo<'/editor/components/attributes/items/AudioAttr', '/editor/components/attributes/items/AudioAttr', Record<never, never>, Record<never, never>>,
    '/editor/components/attributes/items/ImageAttr': RouteRecordInfo<'/editor/components/attributes/items/ImageAttr', '/editor/components/attributes/items/ImageAttr', Record<never, never>, Record<never, never>>,
    '/editor/components/attributes/items/TextAttr': RouteRecordInfo<'/editor/components/attributes/items/TextAttr', '/editor/components/attributes/items/TextAttr', Record<never, never>, Record<never, never>>,
    '/editor/components/attributes/items/VideoAttr': RouteRecordInfo<'/editor/components/attributes/items/VideoAttr', '/editor/components/attributes/items/VideoAttr', Record<never, never>, Record<never, never>>,
    '/editor/components/generate/AudioGenerate': RouteRecordInfo<'/editor/components/generate/AudioGenerate', '/editor/components/generate/AudioGenerate', Record<never, never>, Record<never, never>>,
    '/editor/components/generate/GenerateContainer': RouteRecordInfo<'/editor/components/generate/GenerateContainer', '/editor/components/generate/GenerateContainer', Record<never, never>, Record<never, never>>,
    '/editor/components/generate/ImageGenerate': RouteRecordInfo<'/editor/components/generate/ImageGenerate', '/editor/components/generate/ImageGenerate', Record<never, never>, Record<never, never>>,
    '/editor/components/generate/SpeechGenerate': RouteRecordInfo<'/editor/components/generate/SpeechGenerate', '/editor/components/generate/SpeechGenerate', Record<never, never>, Record<never, never>>,
    '/editor/components/generate/TextGenerate': RouteRecordInfo<'/editor/components/generate/TextGenerate', '/editor/components/generate/TextGenerate', Record<never, never>, Record<never, never>>,
    '/editor/components/generate/VideoGenerate': RouteRecordInfo<'/editor/components/generate/VideoGenerate', '/editor/components/generate/VideoGenerate', Record<never, never>, Record<never, never>>,
    '/editor/components/player/CanvasPlayer': RouteRecordInfo<'/editor/components/player/CanvasPlayer', '/editor/components/player/CanvasPlayer', Record<never, never>, Record<never, never>>,
    '/editor/components/player/item/PlayerControl': RouteRecordInfo<'/editor/components/player/item/PlayerControl', '/editor/components/player/item/PlayerControl', Record<never, never>, Record<never, never>>,
    '/editor/components/player/item/PlayerMoveable': RouteRecordInfo<'/editor/components/player/item/PlayerMoveable', '/editor/components/player/item/PlayerMoveable', Record<never, never>, Record<never, never>>,
    '/editor/components/player/Player': RouteRecordInfo<'/editor/components/player/Player', '/editor/components/player/Player', Record<never, never>, Record<never, never>>,
    '/editor/components/resource/ResourceItem': RouteRecordInfo<'/editor/components/resource/ResourceItem', '/editor/components/resource/ResourceItem', Record<never, never>, Record<never, never>>,
    '/editor/components/resource/ResourceList': RouteRecordInfo<'/editor/components/resource/ResourceList', '/editor/components/resource/ResourceList', Record<never, never>, Record<never, never>>,
    '/editor/components/resource/UploadContainer': RouteRecordInfo<'/editor/components/resource/UploadContainer', '/editor/components/resource/UploadContainer', Record<never, never>, Record<never, never>>,
    '/editor/components/track/item/TimeLine': RouteRecordInfo<'/editor/components/track/item/TimeLine', '/editor/components/track/item/TimeLine', Record<never, never>, Record<never, never>>,
    '/editor/components/track/item/TrackControl': RouteRecordInfo<'/editor/components/track/item/TrackControl', '/editor/components/track/item/TrackControl', Record<never, never>, Record<never, never>>,
    '/editor/components/track/item/TrackHandler': RouteRecordInfo<'/editor/components/track/item/TrackHandler', '/editor/components/track/item/TrackHandler', Record<never, never>, Record<never, never>>,
    '/editor/components/track/item/TrackItem': RouteRecordInfo<'/editor/components/track/item/TrackItem', '/editor/components/track/item/TrackItem', Record<never, never>, Record<never, never>>,
    '/editor/components/track/item/TrackLine': RouteRecordInfo<'/editor/components/track/item/TrackLine', '/editor/components/track/item/TrackLine', Record<never, never>, Record<never, never>>,
    '/editor/components/track/item/TrackListIcon': RouteRecordInfo<'/editor/components/track/item/TrackListIcon', '/editor/components/track/item/TrackListIcon', Record<never, never>, Record<never, never>>,
    '/editor/components/track/item/TrackPlayPoint': RouteRecordInfo<'/editor/components/track/item/TrackPlayPoint', '/editor/components/track/item/TrackPlayPoint', Record<never, never>, Record<never, never>>,
    '/editor/components/track/template/AudioItem': RouteRecordInfo<'/editor/components/track/template/AudioItem', '/editor/components/track/template/AudioItem', Record<never, never>, Record<never, never>>,
    '/editor/components/track/template/ImageItem': RouteRecordInfo<'/editor/components/track/template/ImageItem', '/editor/components/track/template/ImageItem', Record<never, never>, Record<never, never>>,
    '/editor/components/track/template/TextItem': RouteRecordInfo<'/editor/components/track/template/TextItem', '/editor/components/track/template/TextItem', Record<never, never>, Record<never, never>>,
    '/editor/components/track/template/VideoItem': RouteRecordInfo<'/editor/components/track/template/VideoItem', '/editor/components/track/template/VideoItem', Record<never, never>, Record<never, never>>,
    '/editor/components/track/TrackContainer': RouteRecordInfo<'/editor/components/track/TrackContainer', '/editor/components/track/TrackContainer', Record<never, never>, Record<never, never>>,
    '/editor/components/track/TrackList': RouteRecordInfo<'/editor/components/track/TrackList', '/editor/components/track/TrackList', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/components/NewProject': RouteRecordInfo<'/home/components/NewProject', '/home/components/NewProject', Record<never, never>, Record<never, never>>,
    '/home/components/ProjectList': RouteRecordInfo<'/home/components/ProjectList', '/home/components/ProjectList', Record<never, never>, Record<never, never>>,
    '/home/components/UpdateProject': RouteRecordInfo<'/home/components/UpdateProject', '/home/components/UpdateProject', Record<never, never>, Record<never, never>>,
  }
}
